import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { dec } from '@/core/decimal';
import {
  hours,
  kgPerKm,
  metres,
  omrPerHour,
  omrPerKg,
  omrPerKm,
  omrPerUSD,
  percent,
  usdPerTonne,
} from '@/core/units';
import { computeCost } from '@/modules/costing/engine';
import type {
  CommercialTerms,
  Product,
  ResolvedRateSet,
} from '@/modules/costing/types';

/**
 * The parity harness — the most valuable test asset in the project.
 *
 * For each of the 99 costed products, the spreadsheet's own answer is stored
 * as a golden fixture. This test recomputes each one from the imported tables
 * and asserts a match at 4 decimal places.
 *
 * It is how a change to the copper formula, a rate import, or a refactor is
 * proven safe in seconds instead of argued about. It is also the gate on
 * Phase 1 sign-off (PROJECT_PLAN.md, Phase 1 acceptance criterion 1) and,
 * later, the gate on Phase 4's construction model.
 *
 * Fixtures are generated by the importer from the sheets. Until Nuhas confirms
 * the 99 sheets are current and the import runs, the fixture directory is
 * empty and this test reports that rather than passing silently — an empty
 * harness must never read as a green harness.
 */

const FIXTURE_DIR = join(import.meta.dirname, 'fixtures');

interface ParityFixture {
  readonly productId: string;
  readonly designation: string;
  readonly source: string;
  readonly product: SerialisedProduct;
  readonly rates: SerialisedRates;
  readonly terms: SerialisedTerms;
  readonly quantityMetres: string;
  /** What the spreadsheet itself says. The thing we must reproduce. */
  readonly expected: {
    readonly materialsSubtotal: string;
    readonly operationsSubtotal: string;
    readonly overheadsSubtotal: string;
    readonly costPerKm: string;
    readonly costPerMetre: string;
    readonly unitRate: string;
  };
}

interface SerialisedProduct {
  readonly id: string;
  readonly designation: string;
  readonly cores: number;
  readonly sizeMm2: string;
  readonly family: string;
  readonly bom: readonly {
    materialKey: string;
    materialName: string;
    consumption: string;
    scrapPercent: string;
  }[];
  readonly operations: readonly {
    machineKey: string;
    machineName: string;
    sequence: number;
    hoursPerKm: string;
    scalesWithCores: boolean;
  }[];
  readonly overheads: readonly { key: string; name: string; amount: string }[];
}

interface SerialisedRates {
  readonly asOf: string;
  readonly materials: Readonly<Record<string, string>>;
  readonly machines: Readonly<Record<string, string>>;
  readonly lme: string;
  readonly fx: string;
  readonly drawingPremium: Readonly<Record<string, string>>;
}

interface SerialisedTerms {
  readonly marginPercent: string;
  readonly drumCost: string;
  readonly packingCost: string;
  readonly freightCost: string;
}

function loadFixtures(): readonly ParityFixture[] {
  let names: string[];
  try {
    names = readdirSync(FIXTURE_DIR).filter((n) => n.endsWith('.json'));
  } catch {
    return [];
  }
  return names.map(
    (n) => JSON.parse(readFileSync(join(FIXTURE_DIR, n), 'utf8')) as ParityFixture,
  );
}

function hydrateProduct(s: SerialisedProduct): Product {
  return {
    id: s.id,
    designation: s.designation,
    cores: s.cores,
    sizeMm2: dec(s.sizeMm2),
    family: s.family,
    bom: s.bom.map((b) => ({
      materialKey: b.materialKey,
      materialName: b.materialName,
      consumption: kgPerKm(b.consumption),
      scrapPercent: percent(b.scrapPercent),
    })),
    operations: s.operations.map((o) => ({
      machineKey: o.machineKey,
      machineName: o.machineName,
      sequence: o.sequence,
      hoursPerKm: hours(o.hoursPerKm),
      scalesWithCores: o.scalesWithCores,
    })),
    overheads: s.overheads.map((o) => ({
      key: o.key,
      name: o.name,
      amount: omrPerKm(o.amount),
    })),
  };
}

function hydrateRates(s: SerialisedRates): ResolvedRateSet {
  const asOf = new Date(s.asOf);
  const source = (table: string) => ({
    rateId: 'fixture',
    effectiveFrom: asOf,
    table,
  });

  return {
    asOf,
    materials: new Map(
      Object.entries(s.materials).map(([k, v]) => [
        k,
        { rate: omrPerKg(v), source: source('material_rate') },
      ]),
    ),
    machines: new Map(
      Object.entries(s.machines).map(([k, v]) => [
        k,
        { rate: omrPerHour(v), source: source('machine_rate') },
      ]),
    ),
    copper: {
      lme: usdPerTonne(s.lme),
      fx: omrPerUSD(s.fx),
      drawingPremiumBySize: new Map(
        Object.entries(s.drawingPremium).map(([k, v]) => [k, omrPerKg(v)]),
      ),
      source: source('lme_price'),
    },
  };
}

function hydrateTerms(s: SerialisedTerms): CommercialTerms {
  return {
    marginPercent: percent(s.marginPercent),
    drumCost: omrPerKm(s.drumCost),
    packingCost: omrPerKm(s.packingCost),
    freightCost: omrPerKm(s.freightCost),
  };
}

const fixtures = loadFixtures();

/**
 * `pnpm parity` sets this. It is the Phase 1 sign-off gate: with it set, an
 * empty fixture set is a hard failure, because an empty harness reporting
 * green is exactly the failure mode this project cannot afford.
 *
 * Day-to-day `pnpm test` leaves it unset, so the suite stays honest about the
 * fixtures being absent without blocking unrelated work.
 */
const PARITY_REQUIRED = process.env['PARITY_REQUIRED'] === '1';

describe('spreadsheet parity', () => {
  const missing =
    'No parity fixtures. Run the importer against the 99 costed sheets — ' +
    'blocked on Nuhas confirming they are current (PROJECT_PLAN.md §4). ' +
    'Phase 1 cannot be signed off until this passes.';

  it.skipIf(fixtures.length > 0 || !PARITY_REQUIRED)(
    'has fixtures to check',
    () => {
      expect(fixtures.length, missing).toBeGreaterThan(0);
    },
  );

  it.skipIf(fixtures.length > 0)(`awaiting the 99 sheets — ${missing}`, () => {
    expect(fixtures).toHaveLength(0);
  });

  describe.skipIf(fixtures.length === 0)('each costed product', () => {
    for (const fixture of fixtures) {
      it(`${fixture.productId} reproduces ${fixture.source}`, () => {
        const result = computeCost(
          hydrateProduct(fixture.product),
          { metres: metres(fixture.quantityMetres) },
          hydrateRates(fixture.rates),
          hydrateTerms(fixture.terms),
        );

        if (!result.ok) {
          throw new Error(
            `${fixture.productId} could not be priced: ${result.error.message}`,
          );
        }

        const b = result.value;
        const e = fixture.expected;

        // 4 dp — the tolerance the plan commits to. Not "close enough".
        expect(b.materialsSubtotal.toFixed(4)).toBe(dec(e.materialsSubtotal).toFixed(4));
        expect(b.operationsSubtotal.toFixed(4)).toBe(dec(e.operationsSubtotal).toFixed(4));
        expect(b.overheadsSubtotal.toFixed(4)).toBe(dec(e.overheadsSubtotal).toFixed(4));
        expect(b.costPerKm.toFixed(4)).toBe(dec(e.costPerKm).toFixed(4));
        expect(b.costPerMetre.toFixed(4)).toBe(dec(e.costPerMetre).toFixed(4));
        expect(b.unitRate.toFixed(4)).toBe(dec(e.unitRate).toFixed(4));
      });
    }
  });
});
