import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { dec } from '@/core/decimal';
import { metres } from '@/core/units';
import {
  RAW_PRODUCTS,
  SOURCE_LME,
  SOURCE_TERMS,
  hydrateProduct,
  rateSetAt,
} from '@/infra/data';
import { computeCost } from '@/modules/costing/engine';

/**
 * The parity harness — the most valuable test asset in the project.
 *
 * For each of Nuhas's 99 costed products, the source sheet's own answer is a
 * golden fixture generated by `pnpm run import:cost-master`. This test
 * recomputes every product from the imported rate tables and asserts a match.
 *
 * It is how a change to the copper formula, a rate import, or a refactor is
 * proven safe in seconds instead of argued about, and it is the gate on Phase 1
 * sign-off (PROJECT_PLAN.md, Phase 1 acceptance criterion 1).
 *
 * Pricing runs at the LME the source sheets were costed at (USD 4,850/t) —
 * reproducing a sheet means reproducing it on its own inputs. That the same
 * engine then reprices on today's copper is the entire point of the product.
 */

const FIXTURE_DIR = join(import.meta.dirname, 'fixtures');
const AS_OF = new Date('2026-01-01T00:00:00Z');

interface ParityFixture {
  readonly productId: string;
  readonly sourceSheet: string;
  readonly expected: {
    readonly materialsSubtotal: string;
    readonly operationsSubtotal: string;
    readonly overheadsSubtotal: string;
    readonly tooling: string;
    readonly costPerKm: string;
    readonly costPerMetre: string;
    readonly quotePerMetre: string;
    readonly sourceCostPerMetre: string | null;
  };
}

function loadFixtures(): readonly ParityFixture[] {
  try {
    return readdirSync(FIXTURE_DIR)
      .filter((n) => n.endsWith('.json'))
      .map(
        (n) =>
          JSON.parse(readFileSync(join(FIXTURE_DIR, n), 'utf8')) as ParityFixture,
      );
  } catch {
    return [];
  }
}

const fixtures = loadFixtures();

/**
 * Tolerance. The workbook's own reconciliation column shows its recomputation
 * differs from the original sheets by at most 1.9e-4 OMR/m, so the sheets
 * themselves are not internally exact to more than that. We hold the engine to
 * a far tighter bar against the *workbook*, and to the workbook's own bar
 * against the original sheets.
 */
const AGAINST_WORKBOOK_DP = 6;
const AGAINST_ORIGINAL_SHEET = dec('0.0005');

describe('spreadsheet parity', () => {
  it('has a fixture for every imported product', () => {
    // An empty harness reporting green is exactly the failure mode this
    // project cannot afford.
    expect(fixtures.length).toBeGreaterThan(0);
    expect(fixtures.length).toBe(RAW_PRODUCTS.length);
  });

  for (const fixture of fixtures) {
    const raw = RAW_PRODUCTS.find(
      (p) => p.id === fixture.productId && p.sourceSheet === fixture.sourceSheet,
    );

    it(`${fixture.productId} reproduces its cost sheet`, () => {
      expect(raw, `no imported product for ${fixture.productId}`).toBeDefined();
      if (raw === undefined) return;

      const result = computeCost(
        hydrateProduct(raw),
        { metres: metres(1000) },
        rateSetAt(AS_OF, SOURCE_LME),
        SOURCE_TERMS,
      );

      if (!result.ok) {
        throw new Error(
          `${fixture.productId} could not be priced: ${result.error.message}`,
        );
      }

      const b = result.value;
      const e = fixture.expected;

      expect(b.materialsSubtotal.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.materialsSubtotal).toFixed(AGAINST_WORKBOOK_DP),
      );
      expect(b.operationsSubtotal.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.operationsSubtotal).toFixed(AGAINST_WORKBOOK_DP),
      );
      expect(b.overheadsSubtotal.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.overheadsSubtotal).toFixed(AGAINST_WORKBOOK_DP),
      );
      expect(b.tooling.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.tooling).toFixed(AGAINST_WORKBOOK_DP),
      );
      expect(b.costPerKm.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.costPerKm).toFixed(AGAINST_WORKBOOK_DP),
      );
      expect(b.unitRate.toFixed(AGAINST_WORKBOOK_DP)).toBe(
        dec(e.quotePerMetre).toFixed(AGAINST_WORKBOOK_DP),
      );

      // And against the original cost sheet, before this workbook recomputed it.
      if (e.sourceCostPerMetre !== null) {
        const drift = b.costPerMetre.minus(dec(e.sourceCostPerMetre)).abs();
        expect(
          drift.lessThanOrEqualTo(AGAINST_ORIGINAL_SHEET),
          `drifts ${drift.toFixed(8)} OMR/m from the original sheet`,
        ).toBe(true);
      }
    });
  }
});
