import { dec, type Decimal } from '@/core/decimal';
import {
  hours,
  kgPerKm,
  omrPerHour,
  omrPerKg,
  omrPerKm,
  omrPerUSD,
  percent,
  usdPerTonne,
} from '@/core/units';
import type {
  CommercialTerms,
  CopperRate,
  MachineRate,
  MaterialRate,
  Product,
  ResolvedRateSet,
} from '@/modules/costing/types';

import driversJson from './drivers.json';
import machinesJson from './machines.json';
import materialsJson from './materials.json';
import productsJson from './products.json';

/**
 * The imported cost master, hydrated.
 *
 * Generated by `pnpm run import:cost-master` from data/Nuhas_Cost_Master.xlsx —
 * Nuhas's 99 cost sheets consolidated. Every number arrives as a string and is
 * turned into a Decimal here, so no float rounding sits between the
 * spreadsheet and the engine.
 *
 * This module is the seam the database adapter replaces: same shapes, same
 * contract, different source.
 */

interface RawMaterial {
  readonly code: string;
  readonly description: string;
  readonly uom: string;
  readonly lmeLinked: boolean;
  readonly drawingPremium: string | null;
  readonly rate: string;
}

interface RawMachine {
  readonly code: string;
  readonly stage: string;
  readonly rate: string;
  readonly observations: number;
  readonly variancePercent: string | null;
}

interface RawProduct {
  readonly id: string;
  readonly sourceSheet: string;
  readonly designation: string;
  readonly family: string;
  readonly standard: string;
  readonly cores: number;
  readonly sizeMm2: string;
  readonly conductor: string;
  readonly insulation: string;
  readonly screen: string;
  readonly armour: string;
  readonly sheath: string;
  readonly voltage: string;
  readonly toolingPerKm: string;
  readonly bom: readonly {
    materialKey: string;
    materialName: string;
    consumption: string;
    scrap: string;
  }[];
  readonly operations: readonly {
    machineKey: string;
    machineName: string;
    sequence: number;
    hoursPerKm: string;
    cores: number;
  }[];
  readonly overheads: readonly { key: string; name: string; amount: string }[];
}

export const RAW_MATERIALS = materialsJson as readonly RawMaterial[];
export const RAW_MACHINES = machinesJson as readonly RawMachine[];
export const RAW_PRODUCTS = productsJson as readonly RawProduct[];

/** The workbook's drivers: the LME the sheets were costed at, the FX peg, margin. */
export const DRIVERS = {
  lme: usdPerTonne(driversJson.lme),
  fx: omrPerUSD(driversJson.fx),
  marginPercent: percent(driversJson.marginPercent),
};

/**
 * The source sheets were all costed at this LME. Reproducing them requires
 * pricing at it — which is exactly what the parity harness does.
 */
export const SOURCE_LME = DRIVERS.lme;

const rateSource = (rateId: string, table: string) => ({
  rateId,
  effectiveFrom: new Date('2026-01-01T00:00:00Z'),
  table,
});

export function materialRates(): ReadonlyMap<string, MaterialRate> {
  return new Map(
    RAW_MATERIALS.map((m): [string, MaterialRate] => [
      m.code,
      {
        rate: omrPerKg(m.rate),
        lmeLinked: m.lmeLinked,
        ...(m.drawingPremium !== null
          ? { drawingPremium: omrPerKg(m.drawingPremium) }
          : {}),
        source: rateSource(m.code, 'material_rate'),
      },
    ]),
  );
}

export function machineRates(): ReadonlyMap<string, MachineRate> {
  return new Map(
    RAW_MACHINES.map((m): [string, MachineRate] => [
      m.code,
      { rate: omrPerHour(m.rate), source: rateSource(m.code, 'machine_rate') },
    ]),
  );
}

export function copperRate(lme: Decimal = DRIVERS.lme, at?: Date): CopperRate {
  const asOf = at ?? new Date('2026-01-01T00:00:00Z');
  return {
    lme: usdPerTonne(lme),
    fx: DRIVERS.fx,
    source: {
      rateId: `lme-${asOf.toISOString().slice(0, 10)}`,
      effectiveFrom: asOf,
      table: 'lme_price',
    },
  };
}

export function rateSetAt(asOf: Date, lme: Decimal = DRIVERS.lme): ResolvedRateSet {
  return {
    asOf,
    materials: materialRates(),
    machines: machineRates(),
    copper: copperRate(lme, asOf),
  };
}

export function hydrateProduct(raw: RawProduct): Product {
  return {
    id: raw.id,
    sourceSheet: raw.sourceSheet,
    designation: raw.designation,
    family: raw.family,
    spec: {
      cores: raw.cores,
      sizeMm2: dec(raw.sizeMm2),
      conductor: raw.conductor,
      insulation: raw.insulation,
      screen: raw.screen,
      armour: raw.armour,
      sheath: raw.sheath,
      voltage: raw.voltage,
      standard: raw.standard,
    },
    toolingPerKm: omrPerKm(raw.toolingPerKm),
    bom: raw.bom.map((b) => ({
      materialKey: b.materialKey,
      materialName: b.materialName,
      consumption: kgPerKm(b.consumption),
      scrap: kgPerKm(b.scrap),
    })),
    operations: raw.operations.map((o) => ({
      machineKey: o.machineKey,
      machineName: o.machineName,
      sequence: o.sequence,
      hoursPerKm: hours(o.hoursPerKm),
      cores: o.cores,
    })),
    overheads: raw.overheads.map((o) => ({
      key: o.key,
      name: o.name,
      amount: omrPerKm(o.amount),
    })),
  };
}

export function products(): readonly Product[] {
  return RAW_PRODUCTS.map(hydrateProduct);
}

/**
 * Parity terms: margin only, everything else zero. The source sheets stop at
 * cost and margin — they carry no drum, packing, or freight.
 */
export const SOURCE_TERMS: CommercialTerms = {
  marginPercent: DRIVERS.marginPercent,
  drumCost: omrPerKm(0),
  packingCost: omrPerKm(0),
  freightCost: omrPerKm(0),
};
